name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Style check
        run: npm run format-check

      - name: Test
        run: npm test

      - name: Setup BATS
        uses: ./

      - name: BATS test
        run: bats __tests__/integration.bats
